### ISSUE TITLE
Issue when setting up

### ISSUE THREAD

**Issue by broyuken** [tprelog/homeassistant-truenas#1]
I get the following in my logs when I try to install the plugin. I put the IP of my nas, and the api key I generated from the cog icon in truenas. 

Truenas 12
HA 2020.12.2

```
2021-01-06 09:56:52 ERROR (SyncWorker_8) [custom_components.truenas.truenas_report_dev] API FUNCTION ERROR: unknown exception
2021-01-06 09:56:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up truenas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/truenas/sensor.py", line 26, in async_setup_entry
    ExampleSensor(config_entry, coordinator, "Confused"),
  File "/config/custom_components/truenas/sensor.py", line 40, in __init__
    self._name = coordinator.data['sensor_name']
KeyError: 'sensor_name'
```

**Comment by tprelog** [comment]
Hi @broyuken - sorry for the delayed response.

Please understand I'm not a developer, and I'm just learning Python, so even solving simple issues remain a challenge for me. 

Unfortunately, I have not had much time for Python, and even less time to continue work on this integration.

I'm unable to provide any support at this time :disappointed:

**Comment by broyuken** [comment]
No worries, I know you do this in your free time. I ended up using rest commands and got all the info I needed. Thanks for trying to put this together. I’m sure it helped some people out! Keep on learning!
